### ISSUE TITLE
Error when cloning environment -  OSError('raw write() returned invalid length 240...)

### ISSUE THREAD

**Issue by pepaczz** [rohit-patel/Install_Instructions-Win10-Deeplearning-Keras-Tensorflow#1]
When trying to clone the environment, I get the following error.

    OSError('raw write() returned invalid length 240 (should have been between 0 and 120)',)

I assume it is connected to high number of packages to clone:

    conda create --name deeplearning --clone base
    Source:      C:\programs_folder\Anaconda3
    Destination: C:\programs_folder\Anaconda3\envs\deeplearning
    The following packages cannot be cloned out of the root environment:
     - conda-4.4.11-py35_0
     - conda-env-2.6.0-h36134e3_1
    Packages: 228
    Files: 173

Is there a workaround? E.g by copying the package files?

I am running Windows 10 and Anaconda.

**Comment by rohit-ptl** [comment]
@pepaczz I think it is because you are cloning the root environment and it has conda in it, which is not supposed to be there in non-root environments. I think what you are trying to achieve will be achieved by:
``conda create --name deeplearning``
Since that will clone your root without trying to clone conda itself.

**Comment by pepaczz** [comment]
Ah, ok. I was not aware that new environment will use the root packages automatically. It is working now.

Thanks for your help and for the instructions!
